import axios from "axios";

// Lazy-loaded Stability AI config
let stabilityConfig = null;

/**
 * Initialize Stability AI client configuration
 * Free tier available: https://platform.stability.ai/
 */
export const getStabilityConfig = () => {
  if (!stabilityConfig) {
    const apiKey =
      process.env.STABILITY_API_KEY || process.env.STABLE_DIFFUSION_API_KEY;

    if (!apiKey) {
      throw new Error(
        "STABILITY_API_KEY or STABLE_DIFFUSION_API_KEY environment variable is required"
      );
    }

    stabilityConfig = {
      apiKey: apiKey,
      baseURL: "https://api.stability.ai/v1",
      timeout: 60000,
    };
  }
  return stabilityConfig;
};

/**
 * Generate image using Stability AI
 * Models: stable-diffusion-xl-1024-v1-0, stable-diffusion-v1-6, etc.
 * @param {string} prompt - Image generation prompt
 * @param {Object} options - Generation options
 * @returns {Promise<Object>} Image generation result
 */
export const generateStabilityImage = async (prompt, options = {}) => {
  const {
    size = "1024x1024", // 512x512, 640x640, 768x768, 768x1024, 1024x768, 1024x1024
    model = "stable-diffusion-xl-1024-v1-0",
    n = 1, // Number of images (1-4)
    style = null, // 3d-model, analog-film, anime, cinematic, etc.
    seed = null,
  } = options;

  const config = getStabilityConfig();

  try {
    console.log("🎨 Generating image with Stability AI...");

    const requestBody = {
      text_prompts: [
        {
          text: prompt,
          weight: 1,
        },
      ],
      cfg_scale: 7,
      height: parseInt(size.split("x")[1] || "1024"),
      width: parseInt(size.split("x")[0] || "1024"),
      samples: Math.min(n, 4),
      steps: 30,
    };

    if (style) {
      requestBody.style_preset = style;
    }

    if (seed !== null) {
      requestBody.seed = seed;
    }

    const response = await axios.post(
      `${config.baseURL}/generation/${model}/text-to-image`,
      requestBody,
      {
        headers: {
          Authorization: `Bearer ${config.apiKey}`,
          Accept: "application/json",
        },
        timeout: config.timeout,
        responseType: "json",
      }
    );

    if (response.data.artifacts && response.data.artifacts.length > 0) {
      // Stability AI returns base64 images, we need to convert to URL
      // For now, return base64 data URL (client can display directly)
      const images = response.data.artifacts.map((artifact) => ({
        base64: artifact.base64,
        seed: artifact.seed,
      }));

      // Convert first image to data URL
      const imageUrl = `data:image/png;base64,${images[0].base64}`;

      return {
        success: true,
        imageUrl: imageUrl,
        imageUrls: images.map((img) => `data:image/png;base64,${img.base64}`),
        base64Images: images,
        model: model,
        provider: "stability",
      };
    }

    throw new Error("No image generated by Stability AI");
  } catch (error) {
    console.error("❌ Stability AI image generation error:", error.message);
    throw new Error(
      `Stability AI image generation failed: ${
        error.response?.data?.message || error.message
      }`
    );
  }
};

/**
 * Get supported sizes for Stability AI
 */
export const getStabilitySupportedSizes = () => {
  return ["512x512", "640x640", "768x768", "768x1024", "1024x768", "1024x1024"];
};

/**
 * Get supported style presets for Stability AI
 */
export const getStabilitySupportedStyles = () => {
  return [
    "3d-model",
    "analog-film",
    "anime",
    "cinematic",
    "comic-book",
    "digital-art",
    "enhance",
    "fantasy-art",
    "isometric",
    "line-art",
    "low-poly",
    "modeling-compound",
    "neon-punk",
    "origami",
    "photographic",
    "pixel-art",
    "tile-texture",
  ];
};
